apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: datadog-scaledobject
  namespace: integration
spec:
  scaleTargetRef:
    name: binning-service-integration
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: datadog
    # Optional: (Value or AverageValue). Whether the target value is global or average per pod. Default: AverageValue
    metricType: "AverageValue"
    metadata:
      # Required: datadog metric query
      query: "sum:trace.servlet.request.hits{env:integration,service:binning-service-integration}.as_rate()"
      # Required: according to the number of query result, to scale the TargetRef
      queryValue: "0.1"
      # Optional: The time window (in seconds) to retrieve metrics from Datadog. Default: 90
      age: "90"
      # Optional: The metric value to return to the HPA if a metric value wasn't found for the specified time window
      metricUnavailableValue: "0"
    authenticationRef:
      name: keda-trigger-auth-datadog-secret

